version: '3'

services:
  mlflow_server:
    build:
      context: mlflow-server
      dockerfile: Dockerfile
      args:
        MLFLOW_VERSION: "1.4.0"
        PYTHON_VERSION: "3.8"

    environment:
      DB_URI: "postgresql://mlflow@db:5432/mlflow"
      PATH_TO_ARTIFACTS: "/artifacts"
      PATH_TO_TRACKING: "/tracking"
      MLFLOW_PORT: "5000"

    volumes:
    - /var/metrics/1/mlflow/artifacts:/artifacts
    - /var/metrics/1/mlflow/tracking:/tracking

    networks:
    - my_net

    ports:
    - "5000:5000"

    command: sh -c './wait-for-it.sh db:5432 -- ./run'

    restart: always

    depends_on:
    - db

  db:
    image: postgres:12

    environment:
      POSTGRES_USER: mlflow
      POSTGRES_DB: mlflow

    restart: always

    networks:
    - my_net

networks:
  my_net:
    driver: bridge
